import './js/renderList'
import './js/modalAddNote'
import './js/addNotes'
import './js/modalChangeNote'
import './js/changeNote'
import './js/deleteNote'
import './js/archivedNotes'
import './js/renderArhiveList'